# derived from https://github.com/biocore/biom-format/blob/master/.github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "*"

env:
  earliest_python: "3.9"
  latest_python: "3.12"
  miniforge_version: "23.11.0-0"
  miniforge_variant: "Mambaforge"

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.earliest_python }}

      - name: Build distribution
        run: |
          export RELEASE_VERSION=${{ github.ref_name }}
          python setup.py sdist

      - name: Publish distribution
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
